version: "2"
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/nginx-proxy/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    #image: thomastweets/docker-letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx"

networks:
  default:
    external:
      name: nginx-proxy
